version: '3.4'

services:
  swccoursesv2:
    image: swccoursesv2
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "backend/app.js"]
